---
version: '3'


services:
  fast-api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8080:8000 
    volumes:
      - .:/app:ro 
    # env_file:    
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=rahul
      - DATABASE_PASSWORD=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    networks:
      - app-network 


  postgres:
    image: postgres:14.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=rahul
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network 

    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
    driver: local


networks:
  app-network:
    driver: bridge
