---
version: '3.3'
services:
  fast-api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000   #<port on localhost>:<port on container>
    volumes:
      - .:/app:ro    #use to sync the current project 
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload   #to auto reload/restart our application
    env_file:    #we can use both method,(env_file or enviormnent)
      - ./.env
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=rahul
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=rahul_kataria
    
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:

# when we done developing, recommended that  we need to push our latest docker image to docker-hub
# and on the production env we need to pull this image 


   


    