version: '3'
services:
  fast-api:
    build: .
    depends_on:
      - postgres
    ports:
      - 9092:8000   #<port on localhost>:<port on container>
    volumes:
      - ./:/usr/src/app:ro   #use to sync the current project 
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload   #to auto reload/restart our application
    # env_file:    #we can use both method,(env_file or enviormnent)
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=rahul_kataria
      - DATABASE_PASSWORD=rahul
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=rahul
      - POSTGRES_DB=fastapi
    # volumes:
    #   - postgres-db:/var/lib/postgresql/data
# volumes:
#   postgres-db:

# when we done developing, recommended that  we need to push our latest docker image to docker-hub
# and on the production env we need to pull this image 


   


    